package com.caa.backend.mapper;

import com.caa.backend.dto.BoardRequestsDTOS.CreateBoardRequestDTO;
import com.caa.backend.dto.BoardRequestsDTOS.UpdateBoardRequestDTO;
import com.caa.backend.dto.ResponseDTOs.BoardResponseDTO;
import com.caa.backend.model.Board;
import org.mapstruct.*;

import java.util.List;
import java.util.stream.Collectors;

/**
 * MapStruct mapper for Board entity and DTOs
 * Automatically generates implementation at compile time
 */
@Mapper(
        componentModel = "spring",  // Generate as Spring bean
        uses = {PictogramMapper.class},  // Use PictogramMapper for nested conversions
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE  // Don't update null fields
)
public interface BoardMapper {

    // Convert CreateBoardRequest to Board entity
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "pictograms", ignore = true)  // Empty list by default
    @Mapping(target = "createdAt", ignore = true)  // Auto-generated by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true)  // Auto-generated by @UpdateTimestamp
    Board toEntity(CreateBoardRequestDTO request);

    // Update existing Board entity from UpdateBoardRequest
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "pictograms", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntityFromRequest(UpdateBoardRequestDTO request, @MappingTarget Board board);

    // Convert Board entity to BoardResponse (without pictograms)
    @Mapping(target = "totalCells", expression = "java(board.getTotalCells())")
    @Mapping(target = "pictogramCount", expression = "java(board.getPictograms().size())")
    @Mapping(target = "pictograms", ignore = true)  // Don't include pictograms in list view
    @Named("toResponse")
    BoardResponseDTO toResponse(Board board);

    // Convert Board entity to BoardResponse (with pictograms)
    @Mapping(target = "totalCells", expression = "java(board.getTotalCells())")
    @Mapping(target = "pictogramCount", expression = "java(board.getPictograms().size())")
    @Named("toResponseWithPictograms")
    BoardResponseDTO toResponseWithPictograms(Board board);

    // Convert list of Board entities to list of BoardResponse DTOs (without pictograms)
    @Named("toResponseList")
    default List<BoardResponseDTO> toResponseList(List<Board> boards) {
        if (boards == null) {
            return null;
        }
        return boards.stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    /**
     * After mapping hook to ensure data consistency
     */
    @AfterMapping
    default void afterMapping(@MappingTarget BoardResponseDTO response, Board board) {
        // Ensure pictogramCount is set correctly
        if (response.getPictogramCount() == null) {
            response.setPictogramCount(board.getPictograms() != null ?
                    board.getPictograms().size() : 0);
        }

        // Ensure totalCells is calculated
        if (response.getTotalCells() == null) {
            response.setTotalCells(board.getTotalCells());
        }
    }
}