package com.caa.backend.mapper;

import com.caa.backend.dto.ChangeLevelRequestDTO;
import com.caa.backend.dto.ChildProfileRequestDTO;
import com.caa.backend.dto.ResponseDTOs.ChildProfileResponseDTO;
import com.caa.backend.model.ChildProfile;
import org.mapstruct.*;

import java.util.List;
import java.util.stream.Collectors;

/**
 * MapStruct mapper for ChildProfile entity and DTOs
 * Automatically generates implementation at compile time
 */
@Mapper(
        componentModel = "spring",          // Generate as Spring bean
        uses = {BoardMapper.class},         // Use BoardMapper for nested board conversions
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE  // Don't update null fields
)
public interface ChildProfileMapper {
    /**
     * Convert ChildProfileRequestDTO to ChildProfile entity
     * Used when creating a new child profile
     */
    @Mapping(target = "id", ignore = true)          // ID is auto-generated
    @Mapping(target = "tutor", ignore = true)        // Set manually in service after mapping
    @Mapping(target = "assignedBoards", ignore = true) // Empty list by default
    @Mapping(target = "createdAt", ignore = true)   // Auto-generated by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true)   // Auto-generated by @UpdateTimestamp
    @Mapping(target = "level", expression = "java(request.getLevelOrDefault())")  // Default to LEVEL_1
    ChildProfile toEntity(ChildProfileRequestDTO request);

    /**
     * Update existing ChildProfile entity from ChildProfileRequestDTO
     * Only updates non-null fields from request (name, birthDate, photoUrl, level)
     * Does NOT update tutor or assignedBoards — managed separately in service
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "tutor", ignore = true)
    @Mapping(target = "assignedBoards", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntityFromRequest(ChildProfileRequestDTO request, @MappingTarget ChildProfile childProfile);

    /**
     * Update only the level of an existing ChildProfile entity
     * Used in PATCH /api/child-profiles/{id}/level
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "name", ignore = true)
    @Mapping(target = "birthDate", ignore = true)
    @Mapping(target = "photoUrl", ignore = true)
    @Mapping(target = "tutor", ignore = true)
    @Mapping(target = "assignedBoards", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateLevelFromRequest(ChangeLevelRequestDTO request, @MappingTarget ChildProfile childProfile);

    /**
     * Convert ChildProfile entity to ChildProfileResponseDTO (without boards)
     * Used for list views where full board detail is not needed
     */
    @Mapping(target = "tutorId", source = "tutor.id")
    @Mapping(target = "boardCount", expression = "java(childProfile.getAssignedBoards().size())")
    @Mapping(target = "assignedBoards", ignore = true)  // Don't include boards in list view
    @Named("toResponse")
    ChildProfileResponseDTO toResponse(ChildProfile childProfile);

    /**
     * Convert ChildProfile entity to ChildProfileResponseDTO (with boards)
     * Used for detail view where full board information is required
     */
    @Mapping(target = "tutorId", source = "tutor.id")
    @Mapping(target = "boardCount", expression = "java(childProfile.getAssignedBoards().size())")
    @Named("toResponseWithBoards")
    ChildProfileResponseDTO toResponseWithBoards(ChildProfile childProfile);

    /**
     * Convert list of ChildProfile entities to list of ChildProfileResponseDTOs (without boards)
     * Explicitly uses toResponse method to avoid ambiguity
     */
    @Named("toResponseList")
    default List<ChildProfileResponseDTO> toResponseList(List<ChildProfile> childProfiles) {
        if (childProfiles == null) {
            return null;
        }
        return childProfiles.stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    /**
     * After mapping hook to ensure data consistency
     */
    @AfterMapping
    default void afterMapping(@MappingTarget ChildProfileResponseDTO response, ChildProfile childProfile) {
        // Ensure boardCount is set correctly
        if (response.getBoardCount() == null) {
            response.setBoardCount(childProfile.getAssignedBoards() != null ?
                    childProfile.getAssignedBoards().size() : 0);
        }
    }
}
